type EfficiencyData @aws_iam @aws_api_key {
  device_id: String!
  timestamp: Int!
  v_in: Float!
  i_in: Float!
  p_in: Float!
  v_out: Float!
  i_out: Float!
  p_out: Float!
  efficiency: Float!
  status: String
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

input AmplifyAIConversationTurnErrorInput {
  errorType: String!
  message: String!
}

input ModelStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelBooleanInput {
  ne: Boolean
  eq: Boolean
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelSubscriptionStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  in: [String]
  notIn: [String]
}

input ModelSubscriptionIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  in: [Int]
  notIn: [Int]
}

input ModelSubscriptionFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  in: [Float]
  notIn: [Float]
}

input ModelSubscriptionBooleanInput {
  ne: Boolean
  eq: Boolean
}

input ModelSubscriptionIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  in: [ID]
  notIn: [ID]
}

enum ModelAttributeTypes {
  binary
  binarySet
  bool
  list
  map
  number
  numberSet
  string
  stringSet
  _null
}

input ModelSizeInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
}

enum ModelSortDirection {
  ASC
  DESC
}

type ModelEfficiencyDataConnection @aws_api_key @aws_iam {
  items: [EfficiencyData]!
  nextToken: String
}

input ModelEfficiencyDataFilterInput {
  device_id: ModelStringInput
  timestamp: ModelIntInput
  v_in: ModelFloatInput
  i_in: ModelFloatInput
  p_in: ModelFloatInput
  v_out: ModelFloatInput
  i_out: ModelFloatInput
  p_out: ModelFloatInput
  efficiency: ModelFloatInput
  status: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelEfficiencyDataFilterInput]
  or: [ModelEfficiencyDataFilterInput]
  not: ModelEfficiencyDataFilterInput
}

type Query {
  getEfficiencyData(id: ID!): EfficiencyData @aws_api_key @aws_iam
  listEfficiencyData(filter: ModelEfficiencyDataFilterInput, limit: Int, nextToken: String): ModelEfficiencyDataConnection @aws_api_key @aws_iam
  listEfficiencyDataByDevice_idAndTimestamp(device_id: String!, timestamp: ModelIntKeyConditionInput, sortDirection: ModelSortDirection, filter: ModelEfficiencyDataFilterInput, limit: Int, nextToken: String): ModelEfficiencyDataConnection @aws_api_key @aws_iam
}

input ModelEfficiencyDataConditionInput {
  device_id: ModelStringInput
  timestamp: ModelIntInput
  v_in: ModelFloatInput
  i_in: ModelFloatInput
  p_in: ModelFloatInput
  v_out: ModelFloatInput
  i_out: ModelFloatInput
  p_out: ModelFloatInput
  efficiency: ModelFloatInput
  status: ModelStringInput
  and: [ModelEfficiencyDataConditionInput]
  or: [ModelEfficiencyDataConditionInput]
  not: ModelEfficiencyDataConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
}

input CreateEfficiencyDataInput {
  device_id: String!
  timestamp: Int!
  v_in: Float!
  i_in: Float!
  p_in: Float!
  v_out: Float!
  i_out: Float!
  p_out: Float!
  efficiency: Float!
  status: String
  id: ID
}

input UpdateEfficiencyDataInput {
  device_id: String
  timestamp: Int
  v_in: Float
  i_in: Float
  p_in: Float
  v_out: Float
  i_out: Float
  p_out: Float
  efficiency: Float
  status: String
  id: ID!
}

input DeleteEfficiencyDataInput {
  id: ID!
}

type Mutation {
  createEfficiencyData(input: CreateEfficiencyDataInput!, condition: ModelEfficiencyDataConditionInput): EfficiencyData @aws_api_key @aws_iam
  updateEfficiencyData(input: UpdateEfficiencyDataInput!, condition: ModelEfficiencyDataConditionInput): EfficiencyData @aws_api_key @aws_iam
  deleteEfficiencyData(input: DeleteEfficiencyDataInput!, condition: ModelEfficiencyDataConditionInput): EfficiencyData @aws_api_key @aws_iam
}

input ModelSubscriptionEfficiencyDataFilterInput {
  device_id: ModelSubscriptionStringInput
  timestamp: ModelSubscriptionIntInput
  v_in: ModelSubscriptionFloatInput
  i_in: ModelSubscriptionFloatInput
  p_in: ModelSubscriptionFloatInput
  v_out: ModelSubscriptionFloatInput
  i_out: ModelSubscriptionFloatInput
  p_out: ModelSubscriptionFloatInput
  efficiency: ModelSubscriptionFloatInput
  status: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionEfficiencyDataFilterInput]
  or: [ModelSubscriptionEfficiencyDataFilterInput]
}

type Subscription {
  onCreateEfficiencyData(filter: ModelSubscriptionEfficiencyDataFilterInput): EfficiencyData @aws_subscribe(mutations: ["createEfficiencyData"]) @aws_api_key @aws_iam
  onUpdateEfficiencyData(filter: ModelSubscriptionEfficiencyDataFilterInput): EfficiencyData @aws_subscribe(mutations: ["updateEfficiencyData"]) @aws_api_key @aws_iam
  onDeleteEfficiencyData(filter: ModelSubscriptionEfficiencyDataFilterInput): EfficiencyData @aws_subscribe(mutations: ["deleteEfficiencyData"]) @aws_api_key @aws_iam
}

input ModelIntKeyConditionInput {
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
}
